# name: Azure Static Web Apps CI/CD

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened, closed]
#     branches:
#       - main

# jobs:
#   build_and_deploy_job:
#     if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
#     runs-on: windows-latest
#     name: Build and Deploy Job
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: true
#           lfs: false
#       - name: Build And Deploy
#         id: builddeploy
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MOSS_0186B1703 }}
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           action: "upload"
#           app_location: "/src" # Adjusted for Windows-style path
#           api_location: "api" # Api source code path - optional
#           output_location: "/src" # Adjusted for Windows-style path

#   close_pull_request_job:
#     if: github.event_name == 'pull_request' && github.event.action == 'closed'
#     runs-on: windows-latest
#     name: Close Pull Request Job
#     steps:
#       - name: Close Pull Request
#         id: closepullrequest
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MOSS_0186B1703 }}
#           action: "close"
#           app_location: "/src"  # Adjusted for Windows-style pathapi_location: "api"  # Api source code path - optional
#           output_location: "/src"  # Adjusted for Windows-style path

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: windows-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: docker://azure/static-web-apps-deploy:latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MOSS_0186B1703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/src" # Adjusted for Windows-style path
          api_location: "api" # Api source code path - optional
          output_location: "/src" # Adjusted for Windows-style path

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: windows-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: docker://azure/static-web-apps-deploy:latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MOSS_0186B1703 }}
          action: "close"
          app_location: "/src"  # Adjusted for Windows-style pathapi_location: "api"  # Api source code path - optional
          output_location: "/src"  # Adjusted for Windows-style path
